== Lab 10: IT Service Management Suite

This lab will introduce you to a full IT service management suite supporting the ITIL process framework.

Here is the scenario: you are four teams within a larger organization.

Team 1: customer facing ecommerce site
Team 2: back office supply chain/inventory
Team 3: ERP system
Team 4: infrastructure (data center & end user computing)

ssh with X-windows to seis660.gps.stthomas.edu.

If you are going to use X-windows, you should log in with the following options if you are on a Mac:

    ssh -XC -c blowfish-cbc,arcfour  yourID@seis660.gps.stthomas.edu

If you are on a PC using Putty or MobaXterm, you will have a checkbox (that may have defaulted to checked) to enable X. You're on your own to figure out compression options.

Then bring up Firefox over X:

    firefox -XC -no-remote &

then, using that Firefox window, log in to:

http://192.168.33.37/itop

Default user name is "admin," no password. (Don't do this in the real world.)

At the same time, using a LOCAL browser (not the Firefox where you have iTOP), go to the iTop documentation at:

https://wiki.openitop.org/doku.php?id=start

iTop is enterprise software. It consists of many screens that help you add, update, and delete across a complex, shared data model. It is intended as a tool to structure collaboration, in the form of defined processes.



* Set up your teams (disregard existing teams)
** as admin, give each person on your team an ID and password (Configuration Management|Contacts)
** assign each to the appropriate team, named TeamX where X={1-4}

* Set up your configuration items
** Each team has one application solution running on two servers
*** team 1: "ecom"
*** team 2: "s-chain"
*** team 3: "SAP"
*** team 4: "email"




* Work through scripts
** Set up a new service contract
** Execute a Change against a CI
** Initiate and fulfill a service request for access
** Register an Incident against a CI
** Register a Problem against a CI
